### ISSUE TITLE
In cblas_gemm_s8u8s32 function， why the max value of C[i] is 32767?

### ISSUE THREAD

**Issue by LitLeo** [intel/mkl-dnn#518] opened 2019-07-24 10:55 UTC
I am implementing quantization algorithm by  using the cblas_gemm_s8u8s32(). There is example code in mxnet(https://github.com/SterlingJones/mxnet/blob/613033bde2a49a79a7ed1490b61d46aa4165e0a4/src/operator/quantization/quantized_fully_connected.cc)

The tips is "cblas_gemm_s8u8s32 required first matrix must be uint8, shift data from int8(from -128 to 127) to uint8 (from 0 to 255)". 
The activation a is uint8, the weight is int8, and the result c is int32. When I test my code, why the max value of c is 32767?? 32767 is the max value of int16...

I also tested it in mkl examples code (mkl/examples/cblas/source/cblas_gemm_s8u8s32x.c), assign m=1,k=2,n=1, a=[255, 255], b=[127, 127], the c[0] should be 64770, but c[0] = 32767.

Below is my test code, Where am I wrong?

    #include <stdio.h>
    #include <stdlib.h>
    #include "mkl.h"

    int main(int argc, char *argv[])
    {
        MKL_INT         m=1, n=1, k=2;
        MKL_INT         lda=2, ldb=1, ldc=1;
        float           alpha=1.0f, beta=0.0f;
        MKL_INT8        a[2];
        MKL_INT8        b[2];
        MKL_INT32       c[2];

        const MKL_INT8 ao = 0;
        const MKL_INT8 bo = 0;
        MKL_INT32 co = 0;
        CBLAS_OFFSET    offsetc=CblasFixOffset;

        a[0] = 255;
        a[1] = 255;
        b[0] = 127;
        b[1] = 127;
        cblas_gemm_s8u8s32(CblasRowMajor, CblasNoTrans, CblasNoTrans, offsetc,
                          m, n, k, alpha, a, lda, ao, b, ldb, bo, beta, c, ldc, &co);

        printf("\nC: %d\n", c[0]);

          return 0;
    }

**Comment by rsdubtso** [comment] 2019-07-24 13:47
Can you please post `lscpu` output / provide more details about your machine and compiler? I'm getting the expected result. However, I had to change `a` type to `unsigned MKL_INT8` because matrix `A` must be unsigned as the s8u8s32 order applies to col-major; with row-major layout `A` and `B` types are swapped.

**Comment by emfomenk** [comment] 2019-07-24 14:43
I guess @LitLeo uses Skylake server, at least I can reproduce the answer on the machine.
In fact I see the following results:

| platform | result |
|---------|-----|
| Broadwell | 64770 |
| Skylake Server | 32767 |
| Cascade Lake | 64770 |

I think the _incorrect_ result is related to the peculiarity of the  [`VPMADDUBSW`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=VPMADDUBSW&expand=3539) instruction that is used in Int8 GEMM. Please read "[Int8 Computation Aspects](https://intel.github.io/mkl-dnn/dev_guide_int8_computations.html)" from Intel MKL-DNN reference manual that explains this behavior in details.

**Comment by LitLeo** [comment] 2019-07-25 02:03
> Can you please post `lscpu` output / provide more details about your machine and compiler?
> 
> I'm getting the expected result on an `avx2` machine with GCC 8.3 with your code. But, actually you need to change `a` type to `unsigned MKL_INT8` because matrix `A` must be unsigned as the s8u8s32 order applies to col-major layout; with row-major layout `A` and `B` types are swapped.
> 
> ETA: this is somewhat off topic here since the question is about MKL but not MKL-DNN. We're glad to help, but you may get quicker response from the actual BLAS people on the [MKL forum](https://software.intel.com/en-us/forums/intel-math-kernel-library).


> Can you please post `lscpu` output / provide more details about your machine and compiler?
> 
> I'm getting the expected result on an `avx2` machine with GCC 8.3 with your code. But, actually you need to change `a` type to `unsigned MKL_INT8` because matrix `A` must be unsigned as the s8u8s32 order applies to col-major layout; with row-major layout `A` and `B` types are swapped.
> 
> ETA: this is somewhat off topic here since the question is about MKL but not MKL-DNN. We're glad to help, but you may get quicker response from the actual BLAS people on the [MKL forum](https://software.intel.com/en-us/forums/intel-math-kernel-library).

lscpu output:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
Stepping:              1
CPU MHz:               2401.000
BogoMIPS:              4790.37
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13,28-41
NUMA node1 CPU(s):     14-27,42-55
```

Thanks very much. Sorry to bother you because I do not find MKL's github. I will ask MKL questions  on the MKL forum next time.

**Comment by emfomenk** [comment] 2019-07-25 15:22
Hi @LitLeo,

So your system is actually Broadwell. It appears that depending on the version Intel MKL might either use the instruction mentioned above (which leads to the saturation at `int16` level as described in the article) or double precision computations. For performance reasons, I assume, typically Intel MKL will use the `VPMADDUBSW` on Broadwell (AVX2) as well, but the sizes you gave are so small that performance-wise it doesn't really matter what to use -- double precision or the instruction.

So the picture now looks like:

Platform | Intel MKL 2019 Update 2 | Intel MKL 2019 Update 3
-- | -- | --
Broadwell | 32767 | 64770
Skylake Server | 32767 | 32767
Cascade Lake | 64770 | 64770

The conclusion in general is that if you want to avoid potential intermediate saturation you have to make one of the inputs 7-bit integer instead of 8-bit, essentially make the gemm to be `u7s8s32` or `u8s7s32`.

I am closing this issue as the mystery is solved.

**Closed by emfomenk** 2019-07-25 15:22 UTC
Labels: question
