### ISSUE TITLE
Memory leak with 0.16 release of mkldnn with tensorflow

### ISSUE THREAD

**Issue by vignesh-irtt** [intel/mkl-dnn#345] opened 2018-11-07 11:33 UTC
I used the tensorflow wheel provided by **intel** compiled with **mkldnn**
https://storage.googleapis.com/intel-optimized-tensorflow/tensorflow-1.9.0-cp27-cp27mu-linux_x86_64.whl

But there seems a to be a memory leak(ram memory is not being released even after work thread finishes it's work).

we have tried environment variable MKL_DISABLE_FAST_MM=1 but that doesn't solve the problem

**Comment by Galeos93** [comment] 2018-11-15 12:34
@vignesh-irtt Could you fix the memory leak? I am having the same issue but with latest version.

**Comment by vpirogov** [comment] 2018-11-15 15:55
Thanks @sivaranjith. Closing, as the issue is on TF side.

**Closed by vpirogov** 2018-11-15 15:55 UTC
Labels: integration
