### ISSUE TITLE
Test failed on test_mkldnn_threading on Windows

### ISSUE THREAD

**Issue by WakasaKina** [intel/mkl-dnn#343] opened 2018-11-01 14:03 UTC
When I ran `nmake test`, test 34 test_mkldnn_threading failed. The same machine installing fedora can pass all tests.

-----------------------------------------------------------------------------

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
```
Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe pni dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt aes xsave osxsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed
adx smap clflushopt
```
* OS version (`uname -a`)
`Windows 1803 (171134.345)`
* Compiler version (`gcc --version`)
`MSVC 19.15.26730`
* MKLROOT value (`echo MKLROOT=$MKLROOT`)
`c:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl`
* CMake version (`cmake --version`)
`cmake version 3.12.3`
* CMake output log
```
Running tests...
Test project D:/mkl-dnn/build
      Start  1: simple-net-c
 1/42 Test  #1: simple-net-c ..................................   Passed    0.28 sec
      Start  2: simple-net-cpp
 2/42 Test  #2: simple-net-cpp ................................   Passed   19.97 sec
      Start  3: simple-training-net-c
 3/42 Test  #3: simple-training-net-c .........................   Passed    1.25 sec
      Start  4: simple-training-net-cpp
 4/42 Test  #4: simple-training-net-cpp .......................   Passed    1.46 sec
      Start  5: simple-net-int8-cpp
 5/42 Test  #5: simple-net-int8-cpp ...........................   Passed    0.45 sec
      Start  6: simple-rnn-cpp
 6/42 Test  #6: simple-rnn-cpp ................................   Passed   34.68 sec
      Start  7: simple-rnn-training-cpp
 7/42 Test  #7: simple-rnn-training-cpp .......................   Passed    1.76 sec
      Start  8: api-c
 8/42 Test  #8: api-c .........................................   Passed    0.08 sec
      Start  9: test_batch_normalization
 9/42 Test  #9: test_batch_normalization ......................   Passed  367.26 sec
      Start 10: test_concat
10/42 Test #10: test_concat ...................................   Passed    1.63 sec
      Start 11: test_convolution_backward_data_f32
11/42 Test #11: test_convolution_backward_data_f32 ............   Passed  1921.21 sec
      Start 12: test_convolution_backward_data_s16s16s32
12/42 Test #12: test_convolution_backward_data_s16s16s32 ......   Passed  266.24 sec
      Start 13: test_convolution_backward_weights_f32
13/42 Test #13: test_convolution_backward_weights_f32 .........   Passed  2715.02 sec
      Start 14: test_convolution_backward_weights_s16s16s32
14/42 Test #14: test_convolution_backward_weights_s16s16s32 ...   Passed  347.15 sec
      Start 15: test_convolution_format_any
15/42 Test #15: test_convolution_format_any ...................   Passed    1.28 sec
      Start 16: test_convolution_forward_f32
16/42 Test #16: test_convolution_forward_f32 ..................   Passed  1825.97 sec
      Start 17: test_convolution_forward_s16s16s32
17/42 Test #17: test_convolution_forward_s16s16s32 ............   Passed  1973.17 sec
      Start 18: test_convolution_forward_u8s8fp
18/42 Test #18: test_convolution_forward_u8s8fp ...............   Passed    1.28 sec
      Start 19: test_convolution_forward_u8s8s32
19/42 Test #19: test_convolution_forward_u8s8s32 ..............   Passed    1.24 sec
      Start 20: test_convolution_relu_forward_f32
20/42 Test #20: test_convolution_relu_forward_f32 .............   Passed  380.98 sec
      Start 21: test_convolution_relu_forward_neg_slope_f32
21/42 Test #21: test_convolution_relu_forward_neg_slope_f32 ...   Passed  381.33 sec
      Start 22: test_convolution_relu_forward_s16s16s32
22/42 Test #22: test_convolution_relu_forward_s16s16s32 .......   Passed  390.29 sec
      Start 23: test_deconvolution
23/42 Test #23: test_deconvolution ............................   Passed    8.44 sec
      Start 24: test_eltwise
24/42 Test #24: test_eltwise ..................................   Passed  249.01 sec
      Start 25: test_gemm
25/42 Test #25: test_gemm .....................................   Passed  1115.68 sec
      Start 26: test_iface_attr
26/42 Test #26: test_iface_attr ...............................   Passed    1.25 sec
      Start 27: test_iface_pd_iter
27/42 Test #27: test_iface_pd_iter ............................   Passed    1.25 sec
      Start 28: test_inner_product_backward_data
28/42 Test #28: test_inner_product_backward_data ..............   Passed    3.28 sec
      Start 29: test_inner_product_backward_weights
29/42 Test #29: test_inner_product_backward_weights ...........   Passed   27.89 sec
      Start 30: test_inner_product_forward
30/42 Test #30: test_inner_product_forward ....................   Passed    5.88 sec
      Start 31: test_lrn_backward
31/42 Test #31: test_lrn_backward .............................   Passed  177.06 sec
      Start 32: test_lrn_forward
32/42 Test #32: test_lrn_forward ..............................   Passed   66.15 sec
      Start 33: test_memory
33/42 Test #33: test_memory ...................................   Passed    1.23 sec
      Start 34: test_mkldnn_threading
34/42 Test #34: test_mkldnn_threading .........................***Failed  2885.23 sec
      Start 35: test_pooling_backward
35/42 Test #35: test_pooling_backward .........................   Passed  1724.03 sec
      Start 36: test_pooling_forward
36/42 Test #36: test_pooling_forward ..........................   Passed  792.42 sec
      Start 37: test_relu
37/42 Test #37: test_relu .....................................   Passed   22.94 sec
      Start 38: test_reorder
38/42 Test #38: test_reorder ..................................   Passed   28.31 sec
      Start 39: test_shuffle
39/42 Test #39: test_shuffle ..................................   Passed    1.69 sec
      Start 40: test_softmax_backward
40/42 Test #40: test_softmax_backward .........................   Passed   34.63 sec
      Start 41: test_softmax_forward
41/42 Test #41: test_softmax_forward ..........................   Passed   34.70 sec
      Start 42: test_sum
42/42 Test #42: test_sum ......................................   Passed  151.36 sec

98% tests passed, 1 tests failed out of 42

Total Test time (real) = 17971.80 sec

The following tests FAILED:
         34 - test_mkldnn_threading (Failed)
Errors while running CTest
```

When running `./test_mkldnn_threading.exe`

```
[==========] Running 56 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 1 test from test_parallel
[ RUN      ] test_parallel.Test
[       OK ] test_parallel.Test (2 ms)
[----------] 1 test from test_parallel (2 ms total)

[----------] 36 tests from Case0/test_for_nd
[ RUN      ] Case0/test_for_nd.Sequential/0
[       OK ] Case0/test_for_nd.Sequential/0 (0 ms)
[ RUN      ] Case0/test_for_nd.Sequential/1
```

And then:

<img width="352" alt="capture" src="https://user-images.githubusercontent.com/29296362/47857471-a39d8b00-de24-11e8-9fed-3f66d07edff7.PNG">

* git hash (`git log -1 --format=%H`)
`a3e8e7f35d22869b290f4d5b77f52360a823d8dc`

### Actual behavior
Test failed on test_mkldnn_threading

### Expected behavior
Test should be passed

**Comment by vpirogov** [comment] 2018-11-02 19:32
This test does not fail in the nightly validation and might take some time to reproduce.

**Comment by rsdubtso** [comment] 2018-11-06 03:58
I also cannot reproduce this with `MSVC 19.15.26732.1` installed via VS 2017 Community.

@WakasaKina : can you please provide the exact cmake command line and its output? Also, can you please build MKL-DNN with `-DCMAKE_BUILD_TYPE=Debug` and, if it also crashes, run the test under `devenv /debugexe ./test_mkldnn_threading.exe` and see where it crashes?

**Comment by rsdubtso** [comment] 2018-11-06 05:41
@WakasaKina: this issue is already fixed in the latest master in our internal repo. It should be fixed once the changes are pushed to the github. Thanks for the report!

**Comment by rsdubtso** [comment] 2018-11-06 15:14
Apparently, this is already fixed in the github master as well. Closing.

**Closed by rsdubtso** 2018-11-06 15:14 UTC
Labels: bug
