### ISSUE TITLE
Output mismatch in convolution layer with version 0.14

### ISSUE THREAD

**Issue by nhkrishna** [intel/mkl-dnn#488] opened 2019-06-07 10:51 UTC
#### lscpu:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:              4
CPU MHz:               2299.998
BogoMIPS:              4599.99
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch tpr_shadow vnmi flexpriority ept fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap avx512cd xsaveopt xsavec xgetbv1 xsaves arat

#### uname -a:
Linux hari 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3tmwu1 (2018-07-12) x86_64 GNU/Linux

#### gcc --version:
gcc (Debian 6.3.0-18) 6.3.0 20170516

### Problem Description
I have implemented the convolution layer using MKLDNN version 0.14. I have observed incorrect outputs in the machine with above configuration. Same implementation gives correct results with MKLDNN version 0.18. 

Could you please let me know, why MKLDNN with version 0.14 produces the wrong results (or) any fix in the version 0.18 had resolved this issue ?

### Reproduction steps
I have [attached](https://drive.google.com/open?id=1ACHFHcaFFeETtDbkO4Zvsc8XHXbxwkVr) the stand alone convolution layer setup to reproduce this issue in version 0.14 with above mentioned machine configuration for your reference.

Thanks,
Hari

**Comment by vpirogov** [comment] 2019-06-07 14:41
The issue for the shape in question is reproducible with benchdnn in v0.14, so I can confirm that this is a bug.

```
MKLDNN_VERBOSE=1 ./benchdnn mb1_g1ic3oc32_ih224oh112kh3sh2dh0ph0_iw224ow112kw3sw2dw0pw0                                                          
mkldnn_verbose,exec,reorder,simple:any,undef,in:f32_nchw out:f32_nchw,num:1,1x3x224x224,1.60205
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_goihw out:f32_gOhwi16o,num:1,1x32x3x3x3,0.463867
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nchw out:f32_nChw16c,num:1,1x32x112x112,1.47998
mkldnn_verbose,exec,reorder,simple:any,undef,in:f32_x out:f32_x,num:1,32,0.484131
mkldnn_verbose,exec,convolution,jit:avx512_common,forward_inference,fsrc:nchw fwei:gOhwi16o fbia:x fdst:nChw16c,alg:convolution_direct,mb1_g1ic3oc32_ih224oh112kh3sh2dh0ph0_iw224ow112kw3sw2dw0pw0,0.229004
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nChw16c out:f32_nchw,num:1,1x32x112x112,0.943848
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nChw16c out:f32_nchw,num:1,1x32x112x112,0.127197
[  84][DST][0,0,0,0,0,84] fp:   -1307 fp0:   -1307 dt:       0 diff:    1307 rdiff:       1
[  85][DST][0,0,0,0,0,85] fp:    2932 fp0:    2932 dt:       0 diff:    2932 rdiff:       1
[  86][DST][0,0,0,0,0,86] fp:   -2153 fp0:   -2153 dt:     -56 diff:    2097 rdiff: 0.97399
[  87][DST][0,0,0,0,0,87] fp:    -982 fp0:    -982 dt:     -39 diff:     943 rdiff:0.960285
[  88][DST][0,0,0,0,0,88] fp:    -122 fp0:    -122 dt:     -22 diff:     100 rdiff:0.819672
[  89][DST][0,0,0,0,0,89] fp:   -4734 fp0:   -4734 dt:       0 diff:    4734 rdiff:       1
[  90][DST][0,0,0,0,0,90] fp:    4012 fp0:    4012 dt:       0 diff:    4012 rdiff:       1
[  91][DST][0,0,0,0,0,91] fp:     885 fp0:     885 dt:       0 diff:     885 rdiff:       1
[  92][DST][0,0,0,0,0,92] fp:     965 fp0:     965 dt:       0 diff:     965 rdiff:       1
@@@ [DST] final: diff: l0(``941``) l1:(7.62781e+08,5.72471e+08,1.92965e+08,``0.252975``) l2:(1.55931e+06,1.34898e+06,780410,``0.500483``) l8:(8933,8933,8982,``1.00549``)
@@@ error [int conv::doit(const conv::prb_t*, res_t*):568]: 'compare_dst(p, dst, dst_fp, r, true)' -> 1
0:FAILED (errors:103117 total:401408) __REPRO: mb1ic3ih224oc32oh112kh3sh2n"wip"
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:1
```

Pinpointing when it was fixed exactly is not a trivial task, as there's almost a year of development between v0.14 and v0.18. Is there a reason why you cannot update the library version to the latest one?

**Comment by vpirogov** [comment] 2019-06-07 14:58
The issue is in v0.15 and is resolved in v0.16. Looking at the change log I see a bunch of bug fixes related to Intel AVX512 convolution implementation, so it is addressed by one of these.

**Comment by vpirogov** [comment] 2019-06-14 22:15
Closing due to the lack of activity. Feel free to reopen with additional information.

**Closed by vpirogov** 2019-06-14 22:15 UTC
Labels: question

**Comment by nhkrishna** [comment] 2019-06-17 06:16
Thanks for your response @vpirogov. Previously we have created an application that uses v0.14. We can migrate mkldnn version to the v0.18 to make it work.
