### ISSUE TITLE
build log with so many warning info 

### ISSUE THREAD

**Issue by haolongzhangm** [intel/mkl-dnn#559] opened 2019-09-20 10:05 UTC
Here's the place for your question, suggestion, a feature request or brief
description of the problem. If you are submitting a defect report please fill
all the sections below. For everything else feel free to remove everything
below the line.

-----------------------------------------------------------------------------

### Environment
DNNL includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
* OS version (`uname -a`)
* Compiler version (`gcc --version`)
* MKLROOT value (`echo MKLROOT=$MKLROOT`)
* CMake version (`cmake --version`)
* CMake output log
* git hash (`git log -1 --format=%H`)

### Steps to reproduce
Please check that the issue is reproducible with the latest revision on
master. Include all the steps to reproduce the issue. A short C/C++ program
or modified unit tests demonstrating the issue will greatly help
with the investigation.

### Actual behavior
Describe the behavior you see.

### Expected behavior
Describe the behavior you expect.

**Comment by haolongzhangm** [comment] 2019-09-20 10:06
up to now , we can find so many build warning info log, 
can fix all the warning inside?

**Comment by haolongzhangm** [comment] 2019-09-20 10:06
may add build flags : -Werror to stop build after find warning

**Comment by rsdubtso** [comment] 2019-09-20 14:27
Can you please provide MKL-DNN version and steps to reproduce the issue? They are part of the issue template that you need to fill in.

**Comment by haolongzhangm** [comment] 2019-09-22 14:02
version : master with lastest commit

issue flags patch:

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7cb4d09..17091ed 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt

@@ -74,6 +76,7 @@ if(UNIX OR MINGW)
     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99")
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
 endif()
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -fvar-tracking-assignments -Wunused-but-set-parameter")

**Comment by rsdubtso** [comment] 2019-09-23 05:08
Thanks. I see some warnings with some compiler versions, but I am not sure I'm seeing the same ones that you see.

Here's an example:
```
In file included from /redacted/mkl-dnn/src/common/dnnl_traits.hpp:28:0,
                 from /redacted/mkl-dnn/src/common/type_helpers.hpp:26,
                 from /redacted/mkl-dnn/src/common/batch_normalization.cpp:21:
/redacted/mkl-dnn/src/common/utils.hpp: In instantiation of ‘constexpr bool dnnl::impl::utils::one_of(T, P) [with T = std::nullptr_t; P = const dnnl_memory_desc_t*]’:
/redacted/mkl-dnn/src/common/utils.hpp:177:33:   required from ‘constexpr bool dnnl::impl::utils::one_of(T, P, Args ...) [with T = std::nullptr_t; P = dnnl_batch_normalization_desc_t*; Args = {const dnnl_memory_desc_t*}]’
/redacted/mkl-dnn/src/common/utils.hpp:191:18:   required from ‘bool dnnl::impl::utils::any_null(Args ...) [with Args = {dnnl_batch_normalization_desc_t*, const dnnl_memory_desc_t*}]’
/redacted/mkl-dnn/src/common/batch_normalization.cpp:35:58:   required from here
/redacted/mkl-dnn/src/common/utils.hpp:172:25: error: parameter ‘val’ set but not used [-Werror=unused-but-set-parameter]
 constexpr bool one_of(T val, P item) {
                         ^~~
```
This warning appears with gcc 6.x and goes away in 8.x.  The code is correct and does not warrant any warnings, so I believe it is a compiler issue.

If you are observing any different warnings, please post a build log. Otherwise, I'm considering this to be not a bug / issue.

As a workaround, I would suggest not setting `-Wunused-but-set-parameter` when building MKL-DNN.

**Comment by haolongzhangm** [comment] 2019-09-24 02:58
flag ： -fvar-tracking-assignments -Wunused-but-set-parameter  make code have Good robustness

i know the workround with -Wun.....  ; 

any possible to opt code?

**Comment by rsdubtso** [comment] 2019-09-24 03:24
I understand that this warning may be useful. But in this particular case, compiler generates a erroneous warning. I tried a few changes to the code, but the one that silences the warning does not make the code better in any way:

``` diff

diff --git a/src/common/utils.hpp b/src/common/utils.hpp
index d9e54714..b7b62a5e 100644
--- a/src/common/utils.hpp
+++ b/src/common/utils.hpp
@@ -170,7 +170,7 @@ inline bool everyone_is(T val, P item, Args... item_others) {

 template <typename T, typename P>
 constexpr bool one_of(T val, P item) {
-    return val == item;
+    return (void)val, val == item;
 }
 template <typename T, typename P, typename... Args>
 constexpr bool one_of(T val, P item, Args... item_others) {
```

This just forces compiler to think that 'val' is used. Since you are aware of the workaround and since this is clearly a compiler issue, I'm closing this.

**Closed by rsdubtso** 2019-09-24 03:24 UTC
Labels: build, not a bug
