### ISSUE TITLE
Performance Test on MKL-DNN's Winograd convolution

### ISSUE THREAD

**Issue by Mengjintao** [intel/mkl-dnn#372] opened 2018-12-26 08:24 UTC
I am trying to gather the performance results of MKL-DNN's Winograd convolution. But it failed to output any useful results as the direct convolution.  Do you kindly know how to enable the winograd convolution in MKL-DNN and give us a workable evaluation method?

-----------------------------------------------------------------------------

### Environment
* CPU make and model 
Model name:          Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz

* OS version (`uname -a`)
Linux xxx-Intel 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Compiler version (`gcc --version`)
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

* MKLROOT value (`echo MKLROOT=$MKLROOT`)
~/software/mkl-dnn

* CMake version (`cmake --version`)
cmake version 3.10.2

### Steps to reproduce
git clone https://github.com/intel/mkl-dnn.git
cd scripts && ./prepare_mkl.sh && cd ..
mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX=~/software/mkl-dnn/build/install ..
make
make install
./benchdnn --conv  --mode=CORRnPERF  --mb=1 -v3 --cfg=f32 --dir=FWD_D  --alg=WINO ic64ih224iw224_oc64oh224ow224_kh3kw3_sh1sw1ph1pw1

### Actual behavior
@@@ [DST] final: diff: err:2292372, l0(``0.00078125``) l1:(6.32368e+10,6.32368e+10,7238.54,``1.14467e-07``) l2:(4.12175e+07,4.12175e+07,5.67036,``1.37572e-07``) l8:(53450,53450,0.0195312,``3.65412e-07``)
@@@ error [int conv::doit(const conv::prb_t*, res_t*):606]: 'compare_dst(p, dst, dst_fp, r, true)' -> 1
0:FAILED (errors:2292372 total:3211264) __REPRO: --dir=FWD_D --alg=wino mb1ic64ih224oc64oh224kh3ph1n"wip"
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:1
total perf: min(ms):0 avg(ms):-nan

**Comment by emfomenk** [comment] 2018-12-26 08:39
Hi @Mengjintao,

Winograd algorithm by design might slightly affect accuracy. The operations performed are somewhat different than the direct convolution, so you cannot expect identical element-wise results. However, if you look at relative `L1`, `L2`, or `L_infinity` norms you see the difference is pretty small. In your case they are:
```
L1:         1.14467e-07
L2:         1.37572e-07
L_infinity: 3.65412e-07
```

They are pretty close to float `epsilon_0`.

The reason why benchdnn complains is that by default it compares the results element-wise. To change this, you need to pass an extra flag: `--cfg=f32_wino` that we use to check Winograd accuracy. With this flag the test passes:

``` bash
$ export OMP_NUM_THREADS=28
$ export KMP_AFFINITY=granularity=fine,compact 

# run Winograd: --cfg=f32_wino --alg=WINO
$ numactl -l ./tests/benchdnn/benchdnn \
    --conv --mode=CORRnPERF --mb=1 -v3 --dir=FWD_D \
    --cfg=f32_wino --alg=WINO \
    ic64ih224iw224_oc64oh224ow224_kh3kw3_sh1sw1ph1pw1

run: --dir=FWD_D --cfg=f32_wino --alg=wino mb1ic64ih224oc64oh224kh3ph1n"wip"
@@@ [DST] final: diff: err:0, l0(``2.2331e-06``) l1:(7.54384e+11,7.54384e+11,45123.3,``5.98148e-08``) l2:(4.43029e+08,4.43029e+08,40.0032,``9.02949e-08``) l8:(344385,344385,0.15625,``4.53707e-07``)
0:PASSED __REPRO: --dir=FWD_D --cfg=f32_wino --alg=wino mb1ic64ih224oc64oh224kh3ph1n"wip"
perf,"wip",--dir=FWD_D --cfg=f32_wino --alg=wino mb1ic64ih224oc64oh224kh3ph1n"wip",3.67739,2.29456,0.723633,5081.84,0.746703,4924.83
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):0.723633 avg(ms):0.746703

# run direct: --cfg=f32 --alg=DIRECT
$ numactl -l ./tests/benchdnn/benchdnn \
    --conv --mode=CORRnPERF --mb=1 -v3 --dir=FWD_D \
    --cfg=f32 --alg=DIRECT \
    ic64ih224iw224_oc64oh224ow224_kh3kw3_sh1sw1ph1pw1 

run: --dir=FWD_D mb1ic64ih224oc64oh224kh3ph1n"wip"
@@@ [DST] final: diff: err:0, l0(``-0``) l1:(6.32368e+10,6.32368e+10,0,``0``) l2:(4.12175e+07,4.12175e+07,0,``0``) l8:(53450,53450,-0,``-0``)
0:PASSED __REPRO: --dir=FWD_D mb1ic64ih224oc64oh224kh3ph1n"wip"
perf,"wip",--dir=FWD_D mb1ic64ih224oc64oh224kh3ph1n"wip",3.67739,2.29518,1.00781,3648.88,1.01247,3632.1
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):1.00781 avg(ms):1.01247
```

In my case the speed-up from using Winograd is approximately 1.4x (`4.9 TFlops` of Winograd versus `3.6 TFlops` of direct).

**Comment by emfomenk** [comment] 2019-01-03 05:45
Close this for now.
Feel free to reopen or create a new issue if you have any further questions.

**Closed by emfomenk** 2019-01-03 05:45 UTC
Labels: question
