### ISSUE TITLE
Checking asm/linker at cmake time

### ISSUE THREAD

**Issue by WilliamTambellini** [intel/mkl-dnn#507] opened 2019-07-10 20:35 UTC
The main cmake of mkldnn does nt check that the asm/linker is capable to handle the needed asm/avx instructions.
Consequently, when trying to build mkldnn on an OS with an old asm/linker (for instance default centos 6 with bintuils 2.20), building fails with thousand of errors such has:
/tmp/ccsSPMSf.s:59551: Error: suffix or operands invalid for `vpsllq'
....
 
Expected behavior : mkldnn cmake script to check/assert that the linker can handle the targeted asm (avx, avx2, ...) instructions.

Note : I know that upgrading binutils will fix the issue but I just call for a minimum of check at cmake time. Perhaps using cmake try_compile would allow to check that: 
https://cmake.org/cmake/help/v3.13/command/try_compile.html#command:try_compile

-----------------------------------------------------------------------------

### Environment
* CPU make and model :  Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz
* OS version (`uname -a`) : Linux gb100 2.6.32-754.14.2.el6.x86_64 #1 SMP Tue May 14 19:35:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
* Compiler version (`gcc --version`) : gcc 6.1.0
* MKLROOT value (`echo MKLROOT=$MKLROOT`) : none
* CMake version (`cmake --version`) : 3.13
* CMake output log : 

$ ~/buildmkldnn.sh 
-- The C compiler identification is GNU 6.1.0
-- The CXX compiler identification is GNU 6.1.0
-- Check for working C compiler: gcc-6.1.0/bin/gcc
-- Check for working C compiler: gcc-6.1.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: gcc-6.1.0/bin/g++
-- Check for working CXX compiler: gcc-6.1.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- GPU support is disabled
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "1.7.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /local/wtambellini/repos/mkl-dnn/build

* git hash (`git log -1 --format=%H`)
01206f3fc3eb9355d6a1d05cbd054f232306113b

### Steps to reproduce
- git clone mkldnn on centos6
- cmake : see that cmake succeeds
- make : see many errors

### Actual behavior
build failures

### Expected behavior
mkldnn cmake script to test/catch/report the issue at cmake time: For example : "The detected asm/linker (ld/ar) is not capable to handle the targeted ISA for this build."

**Comment by emfomenk** [comment] 2019-07-10 20:50
Hi @WilliamTambellini,

To me that seems like a problem of the installation.
If a simple command:
``` sh
gcc x.c -march=native
```
leads to fail, I don't think that is Intel MKL-DNN's responsibility to handle that.

Anyways, the simple workaround that I might suggest is to use [`MKLDNN_ARCH_OPT_FLAGS=""`](https://intel.github.io/mkl-dnn/dev_guide_build_options.html) or `MKLDNN_ARCH_OPT_FLAGS="-msse4.2"` to avoid avx+ instructions.

**Comment by emfomenk** [comment] 2019-07-10 20:53
BTW, it might happen that `try_compile()` would not be able to catch the problem, since the test source code might not produce the unsupported instructions...

**Comment by WilliamTambellini** [comment] 2019-07-10 21:27
> I don't think that is Intel MKL-DNN's responsibility to handle that.
Well I just propose for mkldnn to early detect that to be more user friendly.
If MKLDNN_ARCH_OPT_FLAGS defaults to using some avx then users should expect the script to check that this is compilable with the asm/linker.

**Comment by WilliamTambellini** [comment] 2019-07-10 21:29
> it might happen that `try_compile()` would not be able to catch the problem, since the test source code might not produce the unsupported instructions

Well if the test source code explicitly tries to run some avx commands then try_compile should fail.

**Comment by emfomenk** [comment] 2019-07-10 21:47
> > it might happen that try_compile() would not be able to catch the problem, since the test source code might not produce the unsupported instructions
>
> Well if the test source code explicitly tries to run some avx commands then try_compile should fail.

Yeah, exactly, here is the thing. Intel MKL-DNN doesn't emit AVX instructions on purpose. It's up to a compiler to generate the optimal code with appropriate instruction. The only *extra* thing that Intel MKL-DNN building system does that it uses `-march=native` as stated in the [documentation](https://intel.github.io/mkl-dnn/dev_guide_build_options.html). And here I assume the cmake should take care of that [1].
I agree that in theory we can extend the cmake default tests with some advanced ones. For instance we can prepare the test program like:
``` c++
int main() {
    float a[16], b[16];
#if defined(_OPENMP)
#pragma omp simd
#endif
    for (int i = 0; i < 16; ++i)
        b[i] += a[i];
    return 0;
}
```

and hope that with `-march=native` the compiler will generate the appropriate instructions and catches the linker/asm issues. But even this test program would not catch the situation when assemblers knows `vaddps` but doesn't know `vpsllq` instruction. So basically my claim is that there is no way to reliably check the toolchain, since the code generated highly depends on the source code itself...

---
[1] Here I on purpose make the linking process to break (because of lack of `main`) of the test program that cmake compiles & runs to make sure the tool chain is fine:

``` sh
$ cmake -DCMAKE_CXX_FLAGS="-Dmain=do_not_execute" ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/usr/bin/c++" is not able to compile a simple test
  program.

  ...
```

**Comment by emfomenk** [comment] 2019-07-10 23:46
After a conversation within the team it seems we agreed to drop the `-march=native` from the default options. That should also the problem you faced with.

**Comment by WilliamTambellini** [comment] 2019-07-11 00:08
Tks. That's probably a good decision : I guess the default build should target generic ISA capable to build/run on a wide majority of setup/hardware. 
Now still, I guess that building will still fail with thousand of asm errors if a "native" arch is desired but the local asm is not compatible with the local CPU ISA.
I guess it would need a minimum of logic in cmake script such as : 
if arch == native and CPU_arch is avx2 capable
  if not check_compile(avx2_build_test.c)
    cmake_fatal("Your compiler/linker/asm is not compatible with the given build options")
...
Nice to have.

**Comment by vpirogov** [comment] 2019-07-11 03:37
The root cause of observed errors is that GCC generates Intel AVX instructions that are not supported by binutils. This behavior has nothing to do with the library, it's pretty much a GCC bug. I don't think that compatibility between GCC and binutils is something that the library build system could reasonably validate.

**Comment by WilliamTambellini** [comment] 2019-07-12 23:28
Well in that case the library ordered gcc to generate asm instructions not compatible with the asm/binutils.
Here, gcc has just done what we asked it to do, generate avx source codes, so I guess gcc did nt do anything wrong. That should by the way apply to any compiler, not only gcc.  
Now, there seems to be a crossplatform find binutils in cmake:  
https://github.com/Kitware/CMake/blob/master/Modules/CMakeFindBinUtils.cmake
Some are even testing inline via cmake if some avx are buildable and runnable:
https://gist.github.com/UnaNancyOwen/263c243ae1e05a2f9d0e

But well, it would need some workload to sustainably validate that the asm/binutils is compatible with the build options so I would understand if that ticket does nt lead to any enhancement in mkldnn cmake script. 
Tks.

**Comment by vpirogov** [comment] 2019-07-16 00:01
If the library were using flags like `-mavx` or Intel AVX intrinsics that require compiler to generate Intel AVX instructions it would be something that the build system should check. This is not the case though, so I don't believe this is something the library should check.

All the cases where Intel MKL-DNN uses instructions explicitly are protected with runtime checks and do not require binutils or compiler support. With that I'm closing the issue.

**Closed by vpirogov** 2019-07-16 00:01 UTC
Labels: sighting
