### ISSUE TITLE
Test failed on windows 10

### ISSUE THREAD

**Issue by rameshkunasi** [intel/mkl-dnn#444] opened 2019-04-01 12:05 UTC
I have compiled MKL-DNN on windows 10. while running default test cases 2 test cases are failed.
1. 18/42 Test #18: test_convolution_forward_f32 ..................***Failed  254.04 sec
2.  33/42 Test #33: test_memory ...................................***Failed    5.89 sec

Will it be problem?

**Comment by rsdubtso** [comment] 2019-04-02 07:35
Yes, this looks like a problem. Please post full testing logs as gists. They are typically found in the Testing directory.

**Comment by rameshkunasi** [comment] 2019-04-02 12:25
Thank you for your reply @rsdubtso ,
I have attached all the logs in Testing directory.

[CTestCostData.txt](https://github.com/intel/mkl-dnn/files/3033866/CTestCostData.txt)
[LastTest.log](https://github.com/intel/mkl-dnn/files/3033867/LastTest.log)
[LastTestsFailed.log](https://github.com/intel/mkl-dnn/files/3033868/LastTestsFailed.log)

**Comment by rsdubtso** [comment] 2019-04-02 16:03
Unfortunately for some reason there's no useful info in these files. Can you please post full information about your system as requested by the issue template?

-----------------------------------------------------------------------------

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
* OS version (`uname -a`)
* Compiler version (`gcc --version`)
* MKLROOT value (`echo MKLROOT=$MKLROOT`)
* CMake version (`cmake --version`)
* CMake output log
* git hash (`git log -1 --format=%H`)

### Steps to reproduce
Please check that the issue is reproducible with the latest revision on
master. Include all the steps to reproduce the issue. A short C/C++ program
or modified unit tests demonstrating the issue will greatly help
with the investigation.

### Actual behavior
Describe the behavior you see.

### Expected behavior
Describe the behavior you expect.

**Comment by rsdubtso** [comment] 2019-04-10 05:17
Closing as there is not enough information to triage this. Feel free to provide more information and reopen this.

**Closed by rsdubtso** 2019-04-10 05:17 UTC
Labels: sighting
