### ISSUE TITLE
floating point exception on Aliyun ECS

### ISSUE THREAD

**Issue by yuewu001** [intel/mkl-dnn#309] opened 2018-08-27 03:38 UTC
When I try to use MKL-DNN with mxnet on Aliyun ECS, i met the "floating point exception" error. I tried both Centos 7.3 and Ubuntu 16.04. Anyone knows the error?

### Steps to reproduce
1. pip install mxnet-mkl
2. python -c 'import mxnet'

### Actual behavior
floating point exception

**Comment by TaoLv** [comment] 2018-08-27 16:13
Hi @yuewu001 , I can't reproduce this issue on my machine. I also don't have any Aliyun ECS instance at hand. So could you try a local machine to see if this problem is still there? Or you can move to https://discuss.mxnet.io/ to attract more attention from the mxnet community. Thanks.

**Comment by yuewu001** [comment] 2018-08-30 05:35
Thanks. @TaoLv I can work with mxnet-mkl-dnn successfully on my local machine. The bug only appears on Aliyun ECS.

**Comment by vpirogov** [comment] 2018-10-01 22:52
Closing the issue as it's not directly related to Intel MKL-DNN.

**Closed by vpirogov** 2018-10-01 22:52 UTC
Labels: integration
