### ISSUE TITLE
Normalization/Pooling tests fail with SegFault

### ISSUE THREAD

**Issue by adamjstewart** [intel/mkl-dnn#680] opened 2020-04-02 19:42 UTC
# Summary

I'm trying to build and test the latest version of DNNL but 4 of the unit tests fail:
```
The following tests FAILED:
	 18 - test_batch_normalization_f32 (SEGFAULT)
	 55 - test_layer_normalization (SEGFAULT)
	 60 - test_pooling_backward (SEGFAULT)
	 61 - test_pooling_forward (SEGFAULT)
Errors while running CTest
make: *** [test] Error 8
```

# Version

DNNL 1.3

# Environment

* CPU make and model: 2.6 GHz Dual-Core Intel Core i5, ivybridge
* OS version: macOS 10.15.4
* Compiler version: Apple Clang 11.0.3
* CMake version: 3.17.0
* CMake output log: [spack-build-out.txt](https://github.com/intel/mkl-dnn/files/4423245/spack-build-out.txt)

# Steps to reproduce

```console
$ spack install --test=root intel-mkl-dnn@1.3
```
Spack builds from source, so this is similar to the usual `cmake`, `make`, `make test`. See the above build log for further details.

# Observed behavior

4 of the tests result in SegFaults.

# Expected behavior

I expect all tests to pass.

Note: I've been having some problems with Clang 11.0.3 lately (PyTorch won't build anymore), so this could be a compiler issue, not a DNNL issue.

**Comment by rsdubtso** [comment] 2020-04-03 01:01
Hm.. Cannot reproduce this without spack. When trying spack, here's what I get
~~~
==> Error: ProcessError: Command exited with status 4:
    './install.sh' '--silent' 'silent.cfg'

1 error found in build log:
  >> 4    ./install.sh: line 74: cd: /private/var/folders/gz/mvvyvp_97qq2w67m_91x9ptc0000gn/T/rsdubtso/spack-stage/spack-stage-intel-mkl-2020.0.166-g2nrw562bwm2xchfzhqks3ai3grgov
          4e/spack-src/./../Resources/pset: No such file or directory
     5    The IA-32 architecture host installation is no longer supported.
     6    The product cannot be installed on this system.
     7    Please refer to product documentation for more information.
     8
     9    Quitting!

See build log for details:
  /var/folders/gz/mvvyvp_97qq2w67m_91x9ptc0000gn/T/rsdubtso/spack-stage/spack-stage-intel-mkl-2020.0.166-g2nrw562bwm2xchfzhqks3ai3grgov4e/spack-build-out.txt

==> Error: Failed to install intel-mkl due to ChildError: ProcessError: Command exited with status 4:
    './install.sh' '--silent' 'silent.cfg'
1 error found in build log:
  >> 4    ./install.sh: line 74: cd: /private/var/folders/gz/mvvyvp_97qq2w67m_91x9ptc0000gn/T/rsdubtso/spack-stage/spack-stage-intel-mkl-2020.0.166-g2nrw562bwm2xchfzhqks3ai3grgov
          4e/spack-src/./../Resources/pset: No such file or directory
     5    The IA-32 architecture host installation is no longer supported.
     6    The product cannot be installed on this system.
     7    Please refer to product documentation for more information.
     8
     9    Quitting!
~~~

I'm running 10.15.4 on a Haswell i5 MBP...
~~~
Darwin mbp-roma.lan 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64 i386 MacBookPro11,1 Darwin
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266
~~~

**Comment by adamjstewart** [comment] 2020-04-03 02:04
> Cannot reproduce this without spack.

Hmm, I'm also unable to reproduce this outside of Spack. I'm guessing the difference is that Spack jumps through hoops to build `llvm-openmp` and link that into the build, since Apple Clang doesn't support OpenMP. See #591. Let me try linking to `llvm-openmp` to confirm this suspicion.

> When trying spack, here's what I get

Looks like there is a bug in our `intel-mkl` package. I usually install that via Intel's dmg's and add it as an external package, so I hadn't encountered that before. I'll see if I can fix that.

**Comment by rsdubtso** [comment] 2020-04-03 03:30
DNNL 1.3 does not depend on intel-mkl at all, so it probably is safe to just drop the dependency.

**Comment by adamjstewart** [comment] 2020-04-03 04:08
Oh, I wonder why we had that dependency in there. In that case, if you run `spack edit intel-mkl-dnn`, comment out the `depends_on('intel-mkl')` line, and build again, are you able to reproduce the bug?

**Comment by rsdubtso** [comment] 2020-04-03 06:29
Well, I got this:
~~~
==> Error: Failed to install intel-mkl-dnn due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j4' 'test'
1 error found in build log:
     1803
     1804    The following tests FAILED:
     1805    	 18 - test_batch_normalization_f32 (SEGFAULT)
     1806    	 60 - test_pooling_backward (SEGFAULT)
     1807    	 61 - test_pooling_forward (SEGFAULT)
     1808    Errors while running CTest
  >> 1809    make: *** [test] Error 8
~~~

But I have no idea how to start looking into this. Any pointers on how to build dnnl standalone with the spack toolchain so that I can at least run a test under a debugger?

**Comment by adamjstewart** [comment] 2020-04-03 13:14
Yes, try this: https://spack-tutorial.readthedocs.io/en/latest/tutorial_packaging.html#debugging-package-builds

**Comment by adamjstewart** [comment] 2020-04-03 14:01
For what it's worth, the TBB build passed all tests. I'll update our Spack package and ping you.

**Comment by adamjstewart** [comment] 2020-04-03 16:01
Okay, I opened up https://github.com/spack/spack/pull/15852 to fix things on our end. As far as I'm concerned, this issue can be closed, as the TBB runtime has no issues for me on macOS. If you want to keep debugging the OMP backend with Apple Clang, you can, but I don't think it's necessary.

**Comment by rsdubtso** [comment] 2020-04-03 16:21
Ok, good. I'll close this since there's only so much time I can spend on this. I think TBB should be fine for most of the cases (caveats documented [here](https://intel.github.io/mkl-dnn/dev_guide_build_options.html)).

**Closed by rsdubtso** 2020-04-03 16:21 UTC
Labels: sighting
