### ISSUE TITLE
mkl-dnn compilation on windows throws error

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#590] opened 2019-11-08 13:10 UTC
Hi,

I have downloaded the mkldnn-1.0.4 used the below commands for build and saw compilation errors 
mkdir build && cd build && cmake -G "Visual Studio 15 2017 Win64" ..
cmake --build .

I have attached the build log [errorLog.txt](https://github.com/intel/mkl-dnn/files/3824679/errorLog.txt)  for your reference. Let me know if I have missed anything.

Thank you,
Praveen.

**Comment by rsdubtso** [comment] 2019-11-08 16:35
Cannot reproduce with Visual Studio 2017 15.9.17 (compiler version 19.16.27034). Quick googling suggests that this may be a compiler issue that was fixed in a later version. ([Example 1](https://developercommunity.visualstudio.com/content/problem/195483/continue-in-constexpr-function-causes-constexpr-fu.html), [Example 2](https://github.com/appveyor/ci/issues/2598)). Therefore, I'm closing this issue.

I would suggest upgrading the compiler. If you have a change that works around this, please feel to post a PR.

**Closed by rsdubtso** 2019-11-08 16:35 UTC
Labels: build, sighting
