### ISSUE TITLE
Is F32 direct 3D convolution supported in AVX512? 

### ISSUE THREAD

**Issue by GalMoore** [intel/mkl-dnn#602] opened 2019-11-25 12:44 UTC
I have a 3D Convolutional Neural Network that I've run on Ubuntu setup with AVX2.  I am now trying to run it on a different system with Suse with AVX512. When I run it with verbose, it looks like the conv ops used are actually AVX2 and not the AVX512 ops I was hoping to see. Is direct 3D convolution supported for AVX512? 

Thanks, 
Gal

**Comment by rsdubtso** [comment] 2019-11-25 14:32
Hi, yes, 3D convolutions should be supported on AVX512 machines. Can you please post `lscpu` and (a portion of) verbose output (see the [issue template](https://github.com/intel/mkl-dnn/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) for more information)

**Comment by eladdidy** [comment] 2019-11-25 17:52
Hi, 
Environment:
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                112
On-line CPU(s) list:   0-111
Thread(s) per core:    2
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8176 CPU @ 2.10GHz
Stepping:              4
CPU MHz:               2800.007
CPU max MHz:           3800.0000
CPU min MHz:           1000.0000
BogoMIPS:              4190.14
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27,56-83
NUMA node1 CPU(s):     28-55,84-111
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb pln pts dtherm hwp hwp_act_window hwp_epp hwp_pkg_req intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc

verbose it attached
[CE.log](https://github.com/intel/mkl-dnn/files/3887939/CE.log)

Thanks
Elad

**Comment by emfomenk** [comment] 2019-11-25 18:54
Could you please confirm you don't force convolution to use any specific format (like `OIhw8i8o` or something)? You should always create a convolution with format tag `any` to allow the implementation to choose the best possible format.

Also, could you please try running [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn) on the target system to check that it will use avx512 implementation?

``` bash
$ export DNNL_VERBOSE=1
$ ./benchdnn --conv mb1_ic20oc50_id1320od1320kd3sd1dd0pd1_ih14oh14kh3sh1dh0ph1_iw8ow8kw3sw1dw0pw1
```

My run gives the following output:
```
...
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_training,src_f32:p:blocked:aBcde16b:f0 wei_f32:p:blocked:ABcde16b16a:f0 bia_f32::blocked:a:f0 dst_f32:p:blocked:aBcde16b:f0,,alg:convolution_direct,mb1_ic20oc50_id1320od1320kd3sd1dd0pd1_ih14oh14kh3sh1dh0ph1_iw8ow8kw3sw1dw0pw1,6.76685
...
```

**Comment by eladdidy** [comment] 2019-11-26 04:43
Hi, 
benchdnn gives me same output.
As for the format tag I run the benchdnn my problem (took it from the verbose log)
`benchdnn --conv mb1_ic2oc20_id1320od1320kd7sd1dd0pd3_ih14oh14kh5sh1dh0ph2_iw8ow8kw5sw1dw0pw2,51.3979`
 and got 

dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_training,src_f32::blocked:abcde:f0 wei_f32:p:blocked:Acdeb16a:f0 bia_f32::blocked:a:f0 dst_f32:p:blocked:aBcde16b:f0,,alg:convolution_direct,mb1_ic2oc20_id1320od1320kd7sd1dd0pd3_ih14oh14kh5sh1dh0ph2_iw8ow8kw5sw1dw0pw2,33.603

I'm using dnnl master from 3 weeks ago.
The model code is auto-generated by ngraph, but I don't see reason not to run AVX512.
Could the post-op 'relu' be the reason? the user scratchpad mode?

**Comment by eladdidy** [comment] 2019-11-26 04:44
i'll print out the first convolution desc

**Comment by tprimak** [comment] 2019-11-26 06:11
Hi @eladdidy. With relu post-op this shape goes to avx512 kernel as well.

./benchdnn --conv **--attr="post_ops='relu'"** mb1_ic2oc20_id1320od1320kd7sd1dd0pd3_ih14oh14kh5sh1dh0ph2_iw8ow8kw5sw1dw0pw2

dnnl_verbose,info,DNNL v1.1.0 (commit 6f458ed7895a49331acfc3f8d3760f8322ecdc1c)
dnnl_verbose,info,Detected ISA is Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,1x2x1320x14x8,0.0949707
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcde:f0 dst_f32:p:blocked:Acdeb16a:f0,,,20x2x7x5x5,0.0852051
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcde:f0 dst_f32:p:blocked:aBcde16b:f0,,,1x20x1320x14x8,0.646973
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:a:f0 dst_f32::blocked:a:f0,,,20,0.0471191
dnnl_verbose,exec,cpu,convolution,**jit:avx512_common**,forward_training,src_f32::blocked:abcde:f0 wei_f32:p:blocked:Acdeb16a:f0 bia_f32::blocked:a:f0 dst_f32:p:blocked:aBcde16b:f0,post_ops:'eltwise_relu;';,alg:convolution_direct,mb1_ic2oc20_id1320od1320kd7sd1dd0pd3_ih14oh14kh5sh1dh0ph2_iw8ow8kw5sw1dw0pw2,1.74707
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32:p:blocked:aBcde16b:f0 dst_f32::blocked:abcde:f0,,,1x20x1320x14x8,0.326172
0:PASSED __REPRO: --conv --attr="post_ops='relu';" mb1ic2id1320ih14iw8oc20od1320oh14ow8kd7kh5kw5pd3ph2pw2

Could you please add verbose log for this convolution when executing in ngraph?

**Comment by rsdubtso** [comment] 2019-11-26 06:22
@tprimak It is there in the third reply: https://github.com/intel/mkl-dnn/issues/602#issuecomment-558267850 (https://github.com/intel/mkl-dnn/files/3887939/CE.log). For some reason, the convolution uses the nCdhw8c format.

**Comment by emfomenk** [comment] 2019-11-27 16:17
> Could the post-op 'relu' be the reason? the user scratchpad mode?

In theory they could be, but on practice they are not. 

I ran all convolutions through benchdnn using the latest and 3-week-old master branch. In both cases I got identical outputs: all convolutions use `jit:avx512_common` (see below).

I think the problem should be attributed to nGraph, hence I am closing this issue.
Please file a bug against them, If you still think the problem is in DNNL, please bring a standalone reproducer we can work with.

---

``` sh
./tests/benchdnn/benchdnn --conv -v5 --attr="post_ops='relu'"  \
  mb1_ic2oc20_id1320od1320kd7sd1dd0pd3_ih14oh14kh5sh1dh0ph2_iw8ow8kw5sw1dw0pw2   \
  mb1_ic20oc20_id1320od1320kd5sd1dd0pd2_ih14oh14kh5sh1dh0ph2_iw8ow8kw5sw1dw0pw2  \
  mb1_ic20oc50_id1320od1320kd3sd1dd0pd1_ih14oh14kh3sh1dh0ph1_iw8ow8kw3sw1dw0pw1  \
  mb1_ic50oc100_id1320od1320kd3sd1dd0pd1_ih14oh14kh3sh1dh0ph1_iw8ow8kw3sw1dw0pw1 \
  mb1_ic100oc2_id1320od1320kd1sd1dd0pd0_ih14oh14kh1sh1dh0ph0_iw8ow8kw1sw1dw0pw0

run: --conv --attr="post_ops='relu';" mb1ic2id1320ih14iw8oc20od1320oh14ow8kd7kh5kw5pd3ph2pw2
dnnl implementation: jit:avx512_common # <-- !!!
@@@ [DST] final: diff: err:0, l0(``-0``) l1:(1.34313e+10,1.34313e+10,0,``0``) l2:(1.50294e+07,1.50294e+07,0,``0``) l8:(34326,34326,-0,``-0``)
0:PASSED __REPRO: --conv --attr="post_ops='relu';" mb1ic2id1320ih14iw8oc20od1320oh14ow8kd7kh5kw5pd3ph2pw2
run: --conv --attr="post_ops='relu';" mb1ic20id1320ih14iw8oc20od1320oh14ow8kd5kh5kw5pd2ph2pw2
dnnl implementation: jit:avx512_common # <-- !!!
@@@ [DST] final: diff: err:0, l0(``-0``) l1:(9.83488e+10,9.83488e+10,0,``0``) l2:(1.08784e+08,1.08784e+08,0,``0``) l8:(232513,232513,-0,``-0``)
1:PASSED __REPRO: --conv --attr="post_ops='relu';" mb1ic20id1320ih14iw8oc20od1320oh14ow8kd5kh5kw5pd2ph2pw2
run: --conv --attr="post_ops='relu';" mb1ic20id1320ih14iw8oc50od1320oh14ow8kd3kh3kw3pd1ph1pw1
dnnl implementation: jit:avx512_common # <-- !!!
@@@ [DST] final: diff: err:0, l0(``0``) l1:(5.98474e+10,5.98474e+10,0,``0``) l2:(4.13945e+07,4.13945e+07,0,``0``) l8:(51451,51451,0,``0``)
2:PASSED __REPRO: --conv --attr="post_ops='relu';" mb1ic20id1320ih14iw8oc50od1320oh14ow8kd3kh3kw3pd1ph1pw1
run: --conv --attr="post_ops='relu';" mb1ic50id1320ih14iw8oc100od1320oh14ow8kd3kh3kw3pd1ph1pw1
dnnl implementation: jit:avx512_common # <-- !!!
@@@ [DST] final: diff: err:0, l0(``0``) l1:(2.99134e+11,2.99134e+11,0,``0``) l2:(1.45877e+08,1.45877e+08,0,``0``) l8:(123804,123804,0,``0``)
3:PASSED __REPRO: --conv --attr="post_ops='relu';" mb1ic50id1320ih14iw8oc100od1320oh14ow8kd3kh3kw3pd1ph1pw1
run: --conv --attr="post_ops='relu';" mb1ic100id1320ih14iw8oc2od1320oh14ow8kd1kh1kw1pd0ph0pw0
dnnl implementation: jit:avx512_common # <-- !!!
@@@ [DST] final: diff: err:0, l0(``0``) l1:(4.48788e+08,4.48788e+08,0,``0``) l2:(1.58834e+06,1.58834e+06,0,``0``) l8:(9568,9568,0,``0``)
4:PASSED __REPRO: --conv --attr="post_ops='relu';" mb1ic100id1320ih14iw8oc2od1320oh14ow8kd1kh1kw1pd0ph0pw0
tests:5 passed:5 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
```

**Closed by emfomenk** 2019-11-27 16:17 UTC
Labels: sighting
